#!/bin/bash

mount -o remount,rw /

sed -i "/^ircddbgateway.*/c ircddbgateway = 20220416_W0CHP-PiStar-Dash" /etc/pistar-release
sed -i "/^dstarrepeater.*/c dstarrepeater = 20220416_W0CHP-PiStar-Dash" /etc/pistar-release

logDateUTC=$(date -u +"%Y-%m-%d")
mmdvmHostLog="/var/log/pi-star/MMDVM-${logDateUTC}.log"

# bail if log or str. doesnt exist yet and use cache until cron-hourly runs this subsequently
if [ ! -f ${mmdvmHostLog} ] ; then
    exit 1
fi
if [[ $( grep -c 'MMDVM protocol version' ${mmdvmHostLog} ) -eq 0 ]]; then
    exit 1
fi

# cache modem info for better performance, rather than parsing logs constantly.
# First, set default FW string vars...
_TCXO=$( grep -m 1 'MMDVM protocol version' ${mmdvmHostLog} | grep  -oi '.*MHz' | tail -1 | rev | cut -d' ' -f 1 | rev )
_FWver=$( grep -m 1 'MMDVM protocol version' ${mmdvmHostLog} | sed 's/(.*)//g' | awk '{print $9}' | tail -1 )
_gitID=$( grep -m 1 'MMDVM protocol version' ${mmdvmHostLog}  | sed 's/(.*)//g'| grep -w 'GitID' | awk '{print $NF}' | tail -1 )
if ! [ -z ${_gitID} ] ; then
    _FWver="${_FWver} ${_gitID}"
else
    _FWver="${_FWver}"
fi
# G4KLX MMDVM FW has a specific string layout. Let's address this.
if grep -w "MMDVM" <<< ${_FWver} > /dev/null ; then
    if ! [ -z ${_gitID} ] ; then
	_FWver="$( grep -m 1 'MMDVM protocol version' ${mmdvmHostLog} | sed 's/(.*)//g' | awk '{print $9 " "  $10}' | tail -1 )"
	_FWver="${_FWver} ${_gitID}"
    else
	_FWver="${_FWver}"
    fi
    if grep -m -1 'MMDVM protocol version' ${mmdvmHostLog} | grep -w 'TCXO' > /dev/null ; then  # defaults to 12.0000MHz
	_TCXO="12.0000MHz"
    else
	_TCXO="$( grep -m -1 -i -o '.*MHz' ${mmdvmHostLog} | tail -1 | rev | cut -d' ' -f 2 | rev )MHz" # newer MMDVM with actual freq. in log line
    fi
fi
# OpenGD77-specific strings...
if grep -w "OpenGD77_HS" <<< ${_FWver} > /dev/null ; then
    _TCXO="14.7456 MHz"
    if ! [ -z ${_gitID} ] ; then
        _FWver="$( grep -m 1 'MMDVM protocol version' ${mmdvmHostLog} | sed 's/(.*)//g' | awk '{print $9 " "  $10}' | tail -1 )"
        _FWver="${_FWver} ${_gitID}"
    else
        _FWver="${_FWver}"
    fi
fi # onto FW using default vars.
if ! grep -q 'Firmware' /etc/pistar-release > /dev/null; then
    sed -i "/Hardware = /a Firmware = \nTCXO = " /etc/pistar-release
    sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
    sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
else
    sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
    sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
fi

countProcs=$(grep -c ^processor /proc/cpuinfo)
if ! grep -w 'ProcNum' /etc/pistar-release > /dev/null; then
    sed -i "/Hardware = /a ProcNum = ${countProcs} " /etc/pistar-release
else
    sed -i "/ProcNum/c ProcNum = ${countProcs}" /etc/pistar-release
fi

_MMDVMHostVer=`MMDVMHost -v | awk '{ print $3 }'`
sed -i "/MMDVMHost/c MMDVMHost = $_MMDVMHostVer" /etc/pistar-release

_KernelVer=`uname -r`
sed -i "/kernel/c kernel = $_KernelVer" /etc/pistar-release

# cleanup last line..
sed -i '${/^$/d}' /etc/pistar-release

