#!/bin/bash
# Restore MMDVM logs during startups (reboots)
# Adopted and modified for W0CHP-PiStar-Dash;
# Original code by KN2TOD <https://github.com/kn2tod/pistar-mmdvm-log-backup-restores>
#

xro=$(grep "/dev/root" /proc/mounts | sed -n "s/.*\(r[ow]\).*/\1/p")
xmv=$(sudo systemctl is-active mmdvmhost.service)

rbt=0
all=0
while getopts ra opt; do
  case $opt in
    r) rbt=1;;
    a) all=1;;
  esac
done
shift $(($OPTIND - 1))

if [ -d /home/pi-star/.backup-mmdvmhost-logs ]; then
    if [ "$xro" == "ro" ]; then
	echo $xro
    fi
    if [ "$xmv" == "active" ]; then
       sudo systemctl stop mmdvmhost.service
    fi
    if [ ! -d /var/log/pi-star ]; then
       sudo mkdir /var/log/pi-star
    fi

    n=3
    if [ $all == 1 ]; then
       n=10000
    fi
    file1="MMDVM"
    file2="/var/log/pi-star/"
    cd /home/pi-star/.backup-mmdvmhost-logs
    for f in $(ls -tr ${file1}* | tail -n $n)
    do
       echo "$f"
       sudo cp -p $f ${file2}$f
    done

    reboot=""
    if [ $rbt == 1 ]; then
       sudo touch /home/pi-star/.backup-mmdvmhost-logs/restore-$(date +%Y-%m-%d-%H:%M:%S)
       reboot="(on reboot)"
    fi

    logger -t "[$$]" "Pi-Star --> MMDVM logs restored $reboot <--"

    if [ "$xmv" == "active" ]; then
       sudo systemctl start mmdvmhost.service
    fi
    if [ "$xro" == "ro" ]; then
	echo $xro
    fi
fi
