#!/bin/bash
#
###############################################################################
#                                                                             #
#                      Pi-Star MMDVMHost Module Tool                          #
#                                                                             #
#     Version 1.4, Code, Design and Development by Andy Taylor (MW0MWZ).      #
#                            Enhanced by W0CHP                                #
#                                                                             #
#    Make it simple to turn on/off modes from the CLI or Cron.                #
#                                                                             #
###############################################################################
#
# Specify some Variables
#
MMDVMCONFIG="/etc/mmdvmhost"
APRSGWCONFIG="/etc/aprsgateway"
SYSCTL_MMDVMHOST="mmdvmhost"
SYSCTL_APRSGW="aprsgateway"
#
# Check to make sure we are root, and bail out if we are not
#
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi
#
# Output some useful information when no variables are passed
#
if [ -z "$1" ]; then
  THIS_SCRIPT=$(basename "$0")
  echo "This script needs arguments, the first should be the"
  echo "mode you want to turn on/off, and the second"
  echo "should be what you want to do with it, either enable or"
  echo "dissable."
  echo ""
  echo "Ex: ${THIS_SCRIPT} D-Star Enable     - enable D-Star mode and restart appropriate daemon"
  echo "Ex: ${THIS_SCRIPT} D-Star Disable    - disable D-Star mode and restart appropriate daemon"
  echo ""
  echo "Valid module names are: D-Star, DMR, YSF, P25, NXDN,"
  echo "                        M17, AX25, POCSAG and APRS"
  echo ""
  exit 0
fi
#
# Check the first Argument
#
if [ "$1" ]; then
  case ${1} in
  ([Dd]-[Ss][Tt][Aa][Rr])
    CUR_STATUS=$(sed -n "/\[D-Star\]/{n;p;}" ${MMDVMCONFIG} | awk -F '=' '{print $2}')
    MODULE="D-Star"
  ;;
  ([Dd][Mm][Rr])
    CUR_STATUS=$(sed -n "/\[DMR\]/{n;p;}" ${MMDVMCONFIG} | awk -F '=' '{print $2}')
    MODULE="DMR"
  ;;
  ([Yy][Ss][Ff])
    CUR_STATUS=$(sed -n "/\[System Fusion\]/{n;p;}" ${MMDVMCONFIG} | awk -F '=' '{print $2}')
    MODULE="System Fusion"
  ;;
  ([Nn][Xx][Dd][Nn])
    CUR_STATUS=$(sed -n "/\[NXDN\]/{n;p;}" ${MMDVMCONFIG} | awk -F '=' '{print $2}')
    MODULE="NXDN"
  ;;
  ([Mm][1][7])
    CUR_STATUS=$(sed -n "/\[M17\]/{n;p;}" ${MMDVMCONFIG} | awk -F '=' '{print $2}')
    MODULE="M17"
  ;;
  ([Pp]25)
    CUR_STATUS=$(sed -n "/\[P25\]/{n;p;}" ${MMDVMCONFIG} | awk -F '=' '{print $2}')
    MODULE="P25"
  ;;
  ([Aa][Xx][2][5])
    CUR_STATUS=$(sed -n "/\[AX 25\]/{n;p;}" ${MMDVMCONFIG} | awk -F '=' '{print $2}')
    MODULE="AX25"
  ;;
  ([Pp][Oo][Cc][Ss][Aa][Gg])
    CUR_STATUS=$(sed -n "/\[POCSAG\]/{n;p;}" ${MMDVMCONFIG} | awk -F '=' '{print $2}')
    MODULE="POCSAG"
  ;;
  ([Aa][Pp][Rr][Ss])
    CUR_STATUS=$(sed -n "/\[Enabled\]/{n;p;}" ${APRSGWCONFIG} | awk -F '=' '{print $2}')
    MODULE="APRS"
  ;;
  *)
    # Catch All
    echo "Unknown Mode ${1}"
    exit 1
  ;;
  esac
fi
#
# Check the second Argument
#
if [ "$2" ]; then
  case ${2} in
  (Enable)
    NEW_STATUS="1"
  ;;
  (Disable)
    NEW_STATUS="0"
  ;;
  *)
    # Catch All
    echo "Unknown option ${2}"
    exit 1
  ;;
  esac
else
  echo "Did you want ${MODULE} to be Enabled or Disabled?"
  exit 1
fi
#
# Is this host configured for MMDVMHost
#
! test -r /etc/dstar-radio.dstarrepeater || exit 1
test -r /etc/dstar-radio.mmdvmhost || exit 1
#
# Flight Checks passed... Do some logic
#
if [ "${CUR_STATUS}" == "${NEW_STATUS}" ]; then
  # Nothing to do
  echo "${MODULE} is already set to ${NEW_STATUS}, nothing to do."
  exit 0
else
  # Change required, so lets change it...
  echo "Setting ${MODULE} to ${NEW_STATUS} and reloading..."
  systemctl stop cron.service > /dev/null 2>/dev/null &
  mount -o remount,rw /
  if [ "${MODULE}" == "APRS" ]; then
      sed -i "/\[Enabled\]/{n;s/${CUR_STATUS}/${NEW_STATUS}/}" ${APRSGWCONFIG}
      systemctl restart ${SYSCTL_APRSGW}
  else
      sed -i "/\[${MODULE}\]/{n;s/${CUR_STATUS}/${NEW_STATUS}/}" ${MMDVMCONFIG}
      systemctl restart ${SYSCTL_MMDVMHOST}
  fi
  if [ "${2}" == "Enable" ] && [ -f "/etc/${1}_paused" ]; then
    rm -rf /etc/${1}_paused
  fi
  if [ "${2}" == "Disable" ] && [ ! -f "/etc/${1}_paused" ]; then
    touch /etc/${1}_paused
  fi
  sleep 1
  mount -o remount,ro /
  systemctl start cron.service > /dev/null 2>/dev/null &
fi
