#!/bin/bash

sed -i "/ircddbgateway/c ircddbgateway = 20190621_W0CHP" /etc/pistar-release
sed -i "/dstarrepeater/c dstarrepeater = 20180911_W0CHP" /etc/pistar-release

mmdvmHostLog="/var/log/pi-star/MMDVM-*.log"

# give a bit of time for MMDVMHost to generate the info in the logs before caching...
while [ ! -f ${mmdvmHostLog} ]
do
    sleep 1
done
while [[ $( grep -c 'MMDVM protocol version' ${mmdvmHostLog} ) -eq 0 ]]
do
    mount -o remount,rw /
    sleep 1
done
mount -o remount,rw /

_FWver=$( grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print $9}' | tail -1 )
_TCXO=$( grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print $11}' | tail -1 | grep -Eo '[0-9]+.[0-9]+MHz' )

if ! grep -q 'Firmware' /etc/pistar-release > /dev/null; then
    sed -i "/Hardware = /a Firmware = \nTCXO = " /etc/pistar-release
    sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
    sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
else
    sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
    sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
fi

# cleanup last line..
sed -i '${/^$/d}' /etc/pistar-release

countProcs=$(grep -c ^processor /proc/cpuinfo)
if ! grep -w 'ProcNum' /etc/pistar-release > /dev/null; then
    sed -i "/Hardware = /a ProcNum = ${countProcs} " /etc/pistar-release
else
    sed -i "/ProcNum/c ProcNum = ${countProcs}" /etc/pistar-release
fi

_MMDVMHostVer=`MMDVMHost -v | awk '{ print $3 }'`
sed -i "/MMDVMHost/c MMDVMHost = $_MMDVMHostVer" /etc/pistar-release

sed -i "/ircddbgateway/c ircddbgateway = 20190621_W0CHP" /etc/pistar-release
sed -i "/dstarrepeater/c dstarrepeater = 20180911_W0CHP" /etc/pistar-release

_KernelVer=`uname -r`
sed -i "/kernel/c kernel = $_KernelVer" /etc/pistar-release
