#!/bin/bash
# Backup MMDVM logs during shutdown/reboots
# Adopted and modified for W0CHP-PiStar-Dash;
# Original code by KN2TOD <https://github.com/kn2tod/pistar-mmdvm-log-backup-restores>
#

if [ ! -d /var/log/pi-star ]; then
  exit 0
fi
xro=$(grep "/dev/root" /proc/mounts | sed -n "s/.*\(r[ow]\).*/\1/p")
if [ "$xro" == "ro" ]; then
  sudo mount -o remount,rw / ; sudo mount -o remount,rw /boot
fi

rbt=0
while getopts ur opt; do
  case $opt in
    r) rbt=1;;
  esac
done
shift $(($OPTIND - 1))

if [ ! -d /home/pi-star/.backup-mmdvmhost-logs ]; then
  sudo mkdir /home/pi-star/.backup-mmdvmhost-logs
fi

cd /var/log/pi-star/
for f in $(ls -tr MMDVM*)
do
  if [ /var/log/pi-star/$f -nt /home/pi-star/.backup-mmdvmhost-logs/$f ]; then
    sudo cp -p /var/log/pi-star/$f /home/pi-star/.backup-mmdvmhost-logs/$f
    echo $f "("$(stat -c %y /home/pi-star/.backup-mmdvmhost-logs/$f | cut -c12-19)") backed up"
  fi
done

if [ $rbt == 1 ]; then
  sudo touch /home/pi-star/.backup-mmdvmhost-logs/reboot-$(date +%Y-%m-%d-%H:%M:%S)
fi

if [ "$xro" == "ro" ]; then
  sudo mount -o remount,ro / ; sudo mount -o remount,ro /boot
fi
