#!/bin/bash

sed -i "/ircddbgateway/c ircddbgateway = 20190621_W0CHP" /etc/pistar-release
sed -i "/dstarrepeater/c dstarrepeater = 20180911_W0CHP" /etc/pistar-release

logDateUTC=$(date -u +"%Y-%m-%d")
mmdvmHostLog="/var/log/pi-star/MMDVM-${logDateUTC}.log"

# give a bit of time for MMDVMHost to generate the info in the logs before caching...
if [ ! -f ${mmdvmHostLog} ] ; then
    echo "no log"
    exit 1
fi

if [[ $( grep -c 'MMDVM protocol version' ${mmdvmHostLog} ) -eq 0 ]]; then
    echo "no string"
    exit 1
fi

mount -o remount,rw /

# First, set default FW string vars...
_FWver=$( grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print $9}' | tail -1 )
_TCXO=$( grep -i -o '.*MHz' ${mmdvmHostLog} | tail -1 | rev | cut -d' ' -f 1 | rev )
# G4KLX MMDVM FW has a specific string layout. Let's address this.
if [ ${_FWver} = "MMDVM" ] ; then
    getColNos=$( grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print NF}' )
    if [ ${getColNos} -ge 16 ]; then # has git id (newer G4KLX fw) in cols 15/16
	_FWver=$( grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print $9 " "  $10 " " $15 " " $16}' | tail -1 )
    else # no gitid; older G4KLX FW
	_FWver=$( grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print $9 " "  $10}' | tail -1 )
    fi
    _TCXO=$( grep -i -o '.*MHz' ${mmdvmHostLog} | tail -1 | rev | cut -d' ' -f 2 | rev )
fi # onto non-G4LKZ FW using default vars.
if ! grep -q 'Firmware' /etc/pistar-release > /dev/null; then
    sed -i "/Hardware = /a Firmware = \nTCXO = " /etc/pistar-release
    sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
    sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
else
    sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
    sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
fi

countProcs=$(grep -c ^processor /proc/cpuinfo)
if ! grep -w 'ProcNum' /etc/pistar-release > /dev/null; then
    sed -i "/Hardware = /a ProcNum = ${countProcs} " /etc/pistar-release
else
    sed -i "/ProcNum/c ProcNum = ${countProcs}" /etc/pistar-release
fi

_MMDVMHostVer=`MMDVMHost -v | awk '{ print $3 }'`
sed -i "/MMDVMHost/c MMDVMHost = $_MMDVMHostVer" /etc/pistar-release

sed -i "/ircddbgateway/c ircddbgateway = 20190621_W0CHP" /etc/pistar-release
sed -i "/dstarrepeater/c dstarrepeater = 20180911_W0CHP" /etc/pistar-release

_KernelVer=`uname -r`
sed -i "/kernel/c kernel = $_KernelVer" /etc/pistar-release

# cleanup last line..
sed -i '${/^$/d}' /etc/pistar-release


