#!/bin/bash

mount -o remount,rw /

# bins are always build in a batch...use MMDVMHost ver as Dstar bin vers...
getVer=$( MMDVMHost -v | cut -d' ' -f 3- )
sed -i "/^ircddbgateway.*/c ircddbgateway = ${getVer}" /etc/pistar-release
sed -i "/^dstarrepeater.*/c dstarrepeater = ${getVer}" /etc/pistar-release

logDateUTC=$(date -u +"%Y-%m-%d")
mmdvmHostLog="/var/log/pi-star/MMDVM-${logDateUTC}.log"

countProcs=$(grep -c ^processor /proc/cpuinfo)
if ! grep -w 'ProcNum' /etc/pistar-release > /dev/null; then
    sed -i "/Hardware = /a ProcNum = ${countProcs} " /etc/pistar-release
else
    sed -i "/ProcNum/c ProcNum = ${countProcs}" /etc/pistar-release
fi

activeIface=$(route | head -3 | tail -1 | awk '{print $8}')
if ! grep -w 'iface' /etc/pistar-release > /dev/null; then
    sed -i "/Hardware = /a iface = ${activeIface} " /etc/pistar-release
else
    sed -i "/iface/c iface = ${activeIface}" /etc/pistar-release
fi

_MMDVMHostVer=`MMDVMHost -v | cut -d' ' -f 3-`
sed -i "/MMDVMHost/c MMDVMHost = $_MMDVMHostVer" /etc/pistar-release

_KernelVer=`uname -r`
sed -i "/kernel/c kernel = $_KernelVer" /etc/pistar-release

# cleanup legacy modem info
if grep -w 'Firmware' /etc/pistar-release > /dev/null; then
    sed -i '/Firmware/d' /etc/pistar-release
fi
if grep -w 'TCXO' /etc/pistar-release > /dev/null; then
    sed -i '/TCXO/d' /etc/pistar-release
fi

PlatDetect=$(/usr/local/sbin/platformDetect.sh)
if ! grep -w 'Platform' /etc/pistar-release > /dev/null; then
    sed -i "/Hardware = /a Platform = ${PlatDetect} " /etc/pistar-release
else
    sed -i "/Platform/c Platform = ${PlatDetect}" /etc/pistar-release
fi

# cleanup last line..
sed -i '${/^$/d}' /etc/pistar-release

