#!/bin/bash
#
##############################################################################
#                                                                            #
#                      Pi-Star NXDNGateway link Tool                         #
#                                                                            #
#     Version 1.0, Code, Design and Development by Andy Taylor (MW0MWZ).     #
#                                                                            #
#       Make it simple to link M17 reflectors from the CLI on Pi-Star.       #
#                                                                            #
##############################################################################
#
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

# Make sure config is present
if [ "$(grep -o 'Remote Commands' /etc/m17gateway | wc -l)" -eq "0" ]; then
  echo -e "Remote Commands not enabled...\n"
  exit 1
fi

# Setup some variables
cmd=/usr/local/bin/RemoteCommand
enable=$(grep -A1 'Remote Commands' /etc/m17gateway | tail -n 1 | awk -F "=" '{print $2}')
port=$(grep -A2 'Remote Commands' /etc/m17gateway | tail -n 1 | awk -F "=" '{print $2}')

# Make sure that remote commands are turned on
if [ "${enable}" -eq "0" ]; then
  echo -e "Remote Commands not enabled...\n"
  exit 1
fi


if [ -z "$1" ]
then
      echo "To unlink from any connected TG, use: pistar-m17link unlink"
      echo "To link to reflector M17-432 module A, use: pistar-m17link M17-432_A"
      echo ""
      exit 0
fi

case ${1} in
unlink)
  (cd /var/log/pi-star/; ${cmd} ${port} Reflector)
  exit 0
;;
*)
  if [ ${#1} -ne 9 ]; then
    echo -e "Invalid target ${1^^}"
    exit 1
  fi
  (cd /var/log/pi-star/; ${cmd} ${port} Reflector ${1^^})
  exit 0
;;
esac

exit 0
